# Generated by Django 5.2.5 on 2025-10-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text='List of user roles. Options: admin, supervisor, member, viewer'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', help_text='Primary role (deprecated - use roles)', max_length=20),
        ),
    ]
