version: "3.9"

services:
  django:
    build: .
    container_name: work_pulse_be_app
    restart: always
    env_file:
      - .env
    environment:
      - WAIT_FOR_DB=true
      - RUN_MIGRATIONS=true
      - DB_PORT=${DB_PORT:-5432}
    ports:
      - "8000:8000"
    depends_on:
      - wait-for-db

  wait-for-db:
    image: alpine
    container_name: work_pulse_be-wait-for-db
    env_file:
      - .env
    command: >
      sh -c "
        apk add --no-cache netcat-openbsd;
        echo Waiting for database...;
        while ! nc -z $DB_HOST ${DB_PORT:-5432}; do
          sleep 2;
        done;
        echo Database is up;
      "
