version: "3.9"

services:
  django:
    build: .
    container_name: work_pulse_be_app
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - wait-for-db
    command: >
      sh -c "
        echo Running migrations... &&
        python manage.py migrate &&
        echo Starting Gunicorn... &&
        gunicorn work_pulse_be.wsgi:application --bind 0.0.0.0:8000
      "

  wait-for-db:
    image: alpine
    container_name: work_pulse_be-wait-for-db
    env_file:
      - .env
    command: >
      sh -c "
        apk add --no-cache netcat-openbsd;
        echo Waiting for database...;
        while ! nc -z $DB_HOST $DB_PORT; do
          sleep 2;
        done;
        echo Database is up;
      "
