# Generated by Django 5.2.5 on 2025-10-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='is_overtime',
            field=models.BooleanField(default=False, help_text='Overtime hours charged at double rate'),
        ),
    ]
