# Generated by Django 5.2.5 on 2025-11-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_timeentry_is_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cc_recipients',
            field=models.TextField(blank=True, help_text='Comma-separated email addresses (max 3)', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('AUD', 'AUD'), ('CHF', 'CHF'), ('CNY', 'CNY'), ('INR', 'INR')], default='CAD', max_length=3),
        ),
        migrations.AddField(
            model_name='client',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time for partial day requests', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='policy',
            field=models.CharField(blank=True, help_text='Policy type (e.g., Personal Time Off (3 Weeks) - Employees)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='requested_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total hours requested', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time for partial day requests', null=True),
        ),
    ]
